export default {
    routes: [
        {
            method: "GET",
            path: "/admin/me",
            handler: "api::document.document.getAppMe",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/documents",
            handler: "api::document.document.findAdminDocuments",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/documents/:id",
            handler: "api::document.document.findAdminDocument",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/audit-logs",
            handler: "api::document.document.findAdminAuditLogs",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/signature-monitoring",
            handler: "api::document.document.findAdminSignatureMonitoring",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/platform-settings",
            handler: "api::document.document.getAdminPlatformSettings",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/platform-settings",
            handler: "api::document.document.updateAdminPlatformSettings",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/notification-templates",
            handler: "api::document.document.findAdminNotificationTemplates",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/reports",
            handler: "api::document.document.getAdminReports",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/reports/export",
            handler: "api::document.document.exportAdminReports",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/archive",
            handler: "api::document.document.findAdminArchive",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/security",
            handler: "api::document.document.getAdminSecurity",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/security/settings",
            handler: "api::document.document.updateAdminSecuritySettings",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/security/users/:id/force-logout",
            handler: "api::document.document.forceLogoutAdminUser",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/archive",
            handler: "api::document.document.archiveAdminDocument",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/restore",
            handler: "api::document.document.restoreAdminDocument",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/documents/:id/archive-export",
            handler: "api::document.document.exportAdminDocumentArchive",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/notification-templates",
            handler: "api::document.document.createAdminNotificationTemplate",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/notification-templates/:id",
            handler: "api::document.document.updateAdminNotificationTemplate",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "DELETE",
            path: "/admin/notification-templates/:id",
            handler: "api::document.document.deleteAdminNotificationTemplate",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/recheck-signatures",
            handler: "api::document.document.recheckAdminDocumentSignatures",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/cancel",
            handler: "api::document.document.cancelAdminDocument",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/reassign-signer",
            handler: "api::document.document.reassignAdminDocumentSigner",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/documents/:id/deadline",
            handler: "api::document.document.updateAdminDocumentDeadline",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/documents/:id/reminder",
            handler: "api::document.document.requestAdminDocumentReminder",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/users",
            handler: "api::document.document.findAdminUsers",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/users",
            handler: "api::document.document.createAdminUser",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/users/:id",
            handler: "api::document.document.updateAdminUser",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/users/:id/password",
            handler: "api::document.document.updateAdminUserPassword",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/users/:id/status",
            handler: "api::document.document.updateAdminUserStatus",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/departments",
            handler: "api::document.document.createAdminDepartment",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/departments/:id",
            handler: "api::document.document.updateAdminDepartment",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "DELETE",
            path: "/admin/departments/:id",
            handler: "api::document.document.deleteAdminDepartment",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/admin/document-types",
            handler: "api::document.document.findAdminDocumentTypes",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/admin/document-types",
            handler: "api::document.document.createAdminDocumentType",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "PUT",
            path: "/admin/document-types/:id",
            handler: "api::document.document.updateAdminDocumentType",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "DELETE",
            path: "/admin/document-types/:id",
            handler: "api::document.document.deleteAdminDocumentType",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/documents/mine",
            handler: "api::document.document.findMine",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/documents/:id/file-url",
            handler: "api::document.document.getFileUrl",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "GET",
            path: "/documents/:id/presign",
            handler: "api::document.document.presignUrl",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/documents/:id/signature-error",
            handler: "api::document.document.reportSignatureError",
            config: { policies: [], middlewares: [] },
        },
        {
            method: "POST",
            path: "/security/heartbeat",
            handler: "api::document.document.recordSecurityHeartbeat",
            config: { policies: [], middlewares: [] },
        },
    ],
};
